import { allMappings } from '../extractor/mapping-loader.js';

export type SupportTier = 'core' | 'experimental' | 'manual-only';

export interface PortalConfig {
  scraperName: string;
  slug: string;
  hosts: string[];
  country: string;
  currency: string;
  localeCode: string;
  areaUnit: string;
  contentSource: 'html' | 'script-json' | 'json-ld' | 'flight-data';
  supportTier: SupportTier;
  expectedExtractionRate?: number;
  stripTrailingSlash: boolean;
  requiresJsRendering: boolean;
}

/**
 * Hardcoded portal registry — serves as the primary source of truth.
 * Portals defined here take precedence over auto-discovered ones.
 */
export const PORTAL_REGISTRY: Record<string, PortalConfig> = {
  uk_rightmove: {
    scraperName: 'uk_rightmove',
    slug: 'uk_rightmove',
    hosts: ['www.rightmove.co.uk', 'rightmove.co.uk'],
    country: 'GB',
    currency: 'GBP',
    localeCode: 'en-GB',
    areaUnit: 'sqft',
    contentSource: 'script-json',
    supportTier: 'core',
    expectedExtractionRate: 0.85,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  es_idealista: {
    scraperName: 'es_idealista',
    slug: 'es_idealista',
    hosts: ['www.idealista.com', 'idealista.com'],
    country: 'ES',
    currency: 'EUR',
    localeCode: 'es-ES',
    areaUnit: 'sqmt',
    contentSource: 'html',
    supportTier: 'manual-only',
    expectedExtractionRate: 0.75,
    stripTrailingSlash: false,
    requiresJsRendering: true,
  },
  uk_zoopla: {
    scraperName: 'uk_zoopla',
    slug: 'uk_zoopla',
    hosts: ['www.zoopla.co.uk', 'zoopla.co.uk'],
    country: 'GB',
    currency: 'GBP',
    localeCode: 'en-GB',
    areaUnit: 'sqft',
    contentSource: 'script-json',
    supportTier: 'core',
    expectedExtractionRate: 0.85,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  us_realtor: {
    scraperName: 'us_realtor',
    slug: 'us_realtor',
    hosts: ['www.realtor.com', 'realtor.com'],
    country: 'US',
    currency: 'USD',
    localeCode: 'en-US',
    areaUnit: 'sqft',
    contentSource: 'flight-data',
    supportTier: 'core',
    expectedExtractionRate: 0.85,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  es_fotocasa: {
    scraperName: 'es_fotocasa',
    slug: 'es_fotocasa',
    hosts: ['www.fotocasa.es', 'fotocasa.es'],
    country: 'ES',
    currency: 'EUR',
    localeCode: 'es-ES',
    areaUnit: 'sqmt',
    contentSource: 'html',
    supportTier: 'core',
    expectedExtractionRate: 0.70,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  es_pisos: {
    scraperName: 'es_pisos',
    slug: 'es_pisos',
    hosts: ['www.pisos.com', 'pisos.com'],
    country: 'ES',
    currency: 'EUR',
    localeCode: 'es-ES',
    areaUnit: 'sqmt',
    contentSource: 'html',
    supportTier: 'core',
    expectedExtractionRate: 0.45,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  in_realestateindia: {
    scraperName: 'in_realestateindia',
    slug: 'in_realestateindia',
    hosts: ['www.realestateindia.com', 'realestateindia.com'],
    country: 'IN',
    currency: 'INR',
    localeCode: 'en-IN',
    areaUnit: 'sqft',
    contentSource: 'html',
    supportTier: 'core',
    expectedExtractionRate: 0.55,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  us_forsalebyowner: {
    scraperName: 'us_forsalebyowner',
    slug: 'us_forsalebyowner',
    hosts: ['www.forsalebyowner.com', 'forsalebyowner.com'],
    country: 'US',
    currency: 'USD',
    localeCode: 'en-US',
    areaUnit: 'sqft',
    contentSource: 'html',
    supportTier: 'core',
    expectedExtractionRate: 0.95,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  uk_jitty: {
    scraperName: 'uk_jitty',
    slug: 'uk_jitty',
    hosts: ['jitty.com', 'www.jitty.com'],
    country: 'GB',
    currency: 'GBP',
    localeCode: 'en-GB',
    areaUnit: 'sqft',
    contentSource: 'html',
    supportTier: 'core',
    expectedExtractionRate: 0.85,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  uk_onthemarket: {
    scraperName: 'uk_onthemarket',
    slug: 'uk_onthemarket',
    hosts: ['www.onthemarket.com', 'onthemarket.com'],
    country: 'GB',
    currency: 'GBP',
    localeCode: 'en-GB',
    areaUnit: 'sqft',
    contentSource: 'html',
    supportTier: 'core',
    expectedExtractionRate: 0.70,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  ie_daft: {
    scraperName: 'ie_daft',
    slug: 'ie_daft',
    hosts: ['www.daft.ie', 'daft.ie'],
    country: 'IE',
    currency: 'EUR',
    localeCode: 'en-IE',
    areaUnit: 'sqmt',
    contentSource: 'html',
    supportTier: 'core',
    expectedExtractionRate: 0.85,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  pt_idealista: {
    scraperName: 'pt_idealista',
    slug: 'pt_idealista',
    hosts: ['www.idealista.pt', 'idealista.pt'],
    country: 'PT',
    currency: 'EUR',
    localeCode: 'pt',
    areaUnit: 'sqmt',
    contentSource: 'script-json',
    supportTier: 'manual-only',
    expectedExtractionRate: 0.90,
    stripTrailingSlash: false,
    requiresJsRendering: true,
  },
  de_immoscout: {
    scraperName: 'de_immoscout',
    slug: 'de_immoscout',
    hosts: ['www.immobilienscout24.de', 'immobilienscout24.de'],
    country: 'DE',
    currency: 'EUR',
    localeCode: 'de-DE',
    areaUnit: 'sqmt',
    contentSource: 'script-json',
    supportTier: 'core',
    expectedExtractionRate: 0.80,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  au_domain: {
    scraperName: 'au_domain',
    slug: 'au_domain',
    hosts: ['www.domain.com.au', 'domain.com.au'],
    country: 'AU',
    currency: 'AUD',
    localeCode: 'en-AU',
    areaUnit: 'sqmt',
    contentSource: 'script-json',
    supportTier: 'core',
    expectedExtractionRate: 0.80,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  au_realestate: {
    scraperName: 'au_realestate',
    slug: 'au_realestate',
    hosts: ['www.realestate.com.au', 'realestate.com.au'],
    country: 'AU',
    currency: 'AUD',
    localeCode: 'en-AU',
    areaUnit: 'sqmt',
    contentSource: 'script-json',
    supportTier: 'core',
    expectedExtractionRate: 0.80,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  us_redfin: {
    scraperName: 'us_redfin',
    slug: 'us_redfin',
    hosts: ['www.redfin.com', 'redfin.com'],
    country: 'US',
    currency: 'USD',
    localeCode: 'en-US',
    areaUnit: 'sqft',
    contentSource: 'html',
    supportTier: 'core',
    expectedExtractionRate: 0.75,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  us_zillow: {
    scraperName: 'us_zillow',
    slug: 'us_zillow',
    hosts: ['www.zillow.com', 'zillow.com'],
    country: 'US',
    currency: 'USD',
    localeCode: 'en-US',
    areaUnit: 'sqft',
    contentSource: 'html',
    supportTier: 'experimental',
    expectedExtractionRate: 0.80,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  us_trulia: {
    scraperName: 'us_trulia',
    slug: 'us_trulia',
    hosts: ['www.trulia.com', 'trulia.com'],
    country: 'US',
    currency: 'USD',
    localeCode: 'en-US',
    areaUnit: 'sqft',
    contentSource: 'script-json',
    supportTier: 'core',
    expectedExtractionRate: 0.75,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  nl_funda: {
    scraperName: 'nl_funda',
    slug: 'nl_funda',
    hosts: ['www.funda.nl', 'funda.nl'],
    country: 'NL',
    currency: 'EUR',
    localeCode: 'nl-NL',
    areaUnit: 'sqmt',
    contentSource: 'html',
    supportTier: 'core',
    expectedExtractionRate: 0.70,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  se_hemnet: {
    scraperName: 'se_hemnet',
    slug: 'se_hemnet',
    hosts: ['www.hemnet.se', 'hemnet.se'],
    country: 'SE',
    currency: 'SEK',
    localeCode: 'sv-SE',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'core',
    expectedExtractionRate: 0.75,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  fr_seloger: {
    scraperName: 'fr_seloger',
    slug: 'fr_seloger',
    hosts: ['www.seloger.com', 'seloger.com'],
    country: 'FR',
    currency: 'EUR',
    localeCode: 'fr-FR',
    areaUnit: 'sqmt',
    contentSource: 'script-json',
    supportTier: 'core',
    expectedExtractionRate: 0.60,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  it_immobiliare: {
    scraperName: 'it_immobiliare',
    slug: 'it_immobiliare',
    hosts: ['www.immobiliare.it', 'immobiliare.it'],
    country: 'IT',
    currency: 'EUR',
    localeCode: 'it-IT',
    areaUnit: 'sqmt',
    contentSource: 'script-json',
    supportTier: 'core',
    expectedExtractionRate: 0.80,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  za_property24: {
    scraperName: 'za_property24',
    slug: 'za_property24',
    hosts: ['www.property24.com', 'property24.com'],
    country: 'ZA',
    currency: 'ZAR',
    localeCode: 'en-ZA',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'core',
    expectedExtractionRate: 0.80,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  be_immoweb: {
    scraperName: 'be_immoweb',
    slug: 'be_immoweb',
    hosts: ['www.immoweb.be', 'immoweb.be'],
    country: 'BE',
    currency: 'EUR',
    localeCode: 'en-BE',
    areaUnit: 'sqmt',
    contentSource: 'script-json',
    supportTier: 'core',
    expectedExtractionRate: 0.80,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  ae_propertyfinder: {
    scraperName: 'ae_propertyfinder',
    slug: 'ae_propertyfinder',
    hosts: ['www.propertyfinder.ae', 'propertyfinder.ae'],
    country: 'AE',
    currency: 'AED',
    localeCode: 'en-AE',
    areaUnit: 'sqft',
    contentSource: 'script-json',
    supportTier: 'core',
    expectedExtractionRate: 0.85,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  mx_inmuebles24: {
    scraperName: 'mx_inmuebles24',
    slug: 'mx_inmuebles24',
    hosts: ['www.inmuebles24.com', 'inmuebles24.com'],
    country: 'MX',
    currency: 'MXN',
    localeCode: 'es-MX',
    areaUnit: 'sqmt',
    contentSource: 'html',
    supportTier: 'core',
    expectedExtractionRate: 0.80,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  ae_bayut: {
    scraperName: 'ae_bayut',
    slug: 'ae_bayut',
    hosts: ['www.bayut.com', 'bayut.com'],
    country: 'AE',
    currency: 'AED',
    localeCode: 'en-AE',
    areaUnit: 'sqft',
    contentSource: 'json-ld',
    supportTier: 'core',
    expectedExtractionRate: 0.80,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  br_zapimoveis: {
    scraperName: 'br_zapimoveis',
    slug: 'br_zapimoveis',
    hosts: ['www.zapimoveis.com.br', 'zapimoveis.com.br'],
    country: 'BR',
    currency: 'BRL',
    localeCode: 'pt-BR',
    areaUnit: 'sqmt',
    contentSource: 'html',
    supportTier: 'core',
    expectedExtractionRate: 0.80,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  pl_otodom: {
    scraperName: 'pl_otodom',
    slug: 'pl_otodom',
    hosts: ['www.otodom.pl', 'otodom.pl'],
    country: 'PL',
    currency: 'PLN',
    localeCode: 'pl-PL',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'core',
    expectedExtractionRate: 0.85,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  at_willhaben: {
    scraperName: 'at_willhaben',
    slug: 'at_willhaben',
    hosts: ['www.willhaben.at', 'willhaben.at'],
    country: 'AT',
    currency: 'EUR',
    localeCode: 'de-AT',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.65,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  dk_boligsiden: {
    scraperName: 'dk_boligsiden',
    slug: 'dk_boligsiden',
    hosts: ['www.boligsiden.dk', 'boligsiden.dk'],
    country: 'DK',
    currency: 'DKK',
    localeCode: 'da-DK',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.65,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  ca_realtor: {
    scraperName: 'ca_realtor',
    slug: 'ca_realtor',
    hosts: ['www.realtor.ca', 'realtor.ca'],
    country: 'CA',
    currency: 'CAD',
    localeCode: 'en-CA',
    areaUnit: 'sqft',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.70,
    stripTrailingSlash: false,
    requiresJsRendering: true,
  },
  nz_trademe: {
    scraperName: 'nz_trademe',
    slug: 'nz_trademe',
    hosts: ['www.trademe.co.nz', 'trademe.co.nz'],
    country: 'NZ',
    currency: 'NZD',
    localeCode: 'en-NZ',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.65,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  sg_propertyguru: {
    scraperName: 'sg_propertyguru',
    slug: 'sg_propertyguru',
    hosts: ['www.propertyguru.com.sg', 'propertyguru.com.sg'],
    country: 'SG',
    currency: 'SGD',
    localeCode: 'en-SG',
    areaUnit: 'sqft',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.70,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  co_fincaraiz: {
    scraperName: 'co_fincaraiz',
    slug: 'co_fincaraiz',
    hosts: ['www.fincaraiz.com.co', 'fincaraiz.com.co'],
    country: 'CO',
    currency: 'COP',
    localeCode: 'es-CO',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.65,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  tr_sahibinden: {
    scraperName: 'tr_sahibinden',
    slug: 'tr_sahibinden',
    hosts: ['www.sahibinden.com', 'sahibinden.com'],
    country: 'TR',
    currency: 'TRY',
    localeCode: 'tr-TR',
    areaUnit: 'sqmt',
    contentSource: 'html',
    supportTier: 'experimental',
    expectedExtractionRate: 0.65,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  gr_spitogatos: {
    scraperName: 'gr_spitogatos',
    slug: 'gr_spitogatos',
    hosts: ['www.spitogatos.gr', 'spitogatos.gr'],
    country: 'GR',
    currency: 'EUR',
    localeCode: 'el-GR',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.60,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  ar_zonaprop: {
    scraperName: 'ar_zonaprop',
    slug: 'ar_zonaprop',
    hosts: ['www.zonaprop.com.ar', 'zonaprop.com.ar'],
    country: 'AR',
    currency: 'USD',
    localeCode: 'es-AR',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.70,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  cl_portalinmobiliario: {
    scraperName: 'cl_portalinmobiliario',
    slug: 'cl_portalinmobiliario',
    hosts: ['www.portalinmobiliario.com', 'portalinmobiliario.com'],
    country: 'CL',
    currency: 'CLP',
    localeCode: 'es-CL',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.70,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  th_ddproperty: {
    scraperName: 'th_ddproperty',
    slug: 'th_ddproperty',
    hosts: ['www.ddproperty.com', 'ddproperty.com'],
    country: 'TH',
    currency: 'THB',
    localeCode: 'th-TH',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.65,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  ph_lamudi: {
    scraperName: 'ph_lamudi',
    slug: 'ph_lamudi',
    hosts: ['www.lamudi.com.ph', 'lamudi.com.ph'],
    country: 'PH',
    currency: 'PHP',
    localeCode: 'en-PH',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.65,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  ke_buyrentkenya: {
    scraperName: 'ke_buyrentkenya',
    slug: 'ke_buyrentkenya',
    hosts: ['www.buyrentkenya.com', 'buyrentkenya.com'],
    country: 'KE',
    currency: 'KES',
    localeCode: 'en-KE',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.60,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  ng_propertypro: {
    scraperName: 'ng_propertypro',
    slug: 'ng_propertypro',
    hosts: ['www.propertypro.ng', 'propertypro.ng'],
    country: 'NG',
    currency: 'NGN',
    localeCode: 'en-NG',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.60,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  ru_cian: {
    scraperName: 'ru_cian',
    slug: 'ru_cian',
    hosts: ['www.cian.ru', 'cian.ru'],
    country: 'RU',
    currency: 'RUB',
    localeCode: 'ru-RU',
    areaUnit: 'sqmt',
    contentSource: 'html',
    supportTier: 'experimental',
    expectedExtractionRate: 0.60,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  in_magicbricks: {
    scraperName: 'in_magicbricks',
    slug: 'in_magicbricks',
    hosts: ['www.magicbricks.com', 'magicbricks.com'],
    country: 'IN',
    currency: 'INR',
    localeCode: 'en-IN',
    areaUnit: 'sqft',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.65,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  my_propertyguru: {
    scraperName: 'my_propertyguru',
    slug: 'my_propertyguru',
    hosts: ['www.propertyguru.com.my', 'propertyguru.com.my'],
    country: 'MY',
    currency: 'MYR',
    localeCode: 'en-MY',
    areaUnit: 'sqft',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.65,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  hk_squarefoot: {
    scraperName: 'hk_squarefoot',
    slug: 'hk_squarefoot',
    hosts: ['www.squarefoot.com.hk', 'squarefoot.com.hk'],
    country: 'HK',
    currency: 'HKD',
    localeCode: 'en-HK',
    areaUnit: 'sqft',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.60,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  fi_oikotie: {
    scraperName: 'fi_oikotie',
    slug: 'fi_oikotie',
    hosts: ['www.oikotie.fi', 'oikotie.fi'],
    country: 'FI',
    currency: 'EUR',
    localeCode: 'fi-FI',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.60,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  no_finn: {
    scraperName: 'no_finn',
    slug: 'no_finn',
    hosts: ['www.finn.no', 'finn.no'],
    country: 'NO',
    currency: 'NOK',
    localeCode: 'nb-NO',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.65,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  ch_immoscout: {
    scraperName: 'ch_immoscout',
    slug: 'ch_immoscout',
    hosts: ['www.immoscout24.ch', 'immoscout24.ch'],
    country: 'CH',
    currency: 'CHF',
    localeCode: 'de-CH',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.65,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  ie_myhome: {
    scraperName: 'ie_myhome',
    slug: 'ie_myhome',
    hosts: ['www.myhome.ie', 'myhome.ie'],
    country: 'IE',
    currency: 'EUR',
    localeCode: 'en-IE',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.65,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  eg_propertyfinder: {
    scraperName: 'eg_propertyfinder',
    slug: 'eg_propertyfinder',
    hosts: ['www.propertyfinder.eg', 'propertyfinder.eg'],
    country: 'EG',
    currency: 'EGP',
    localeCode: 'en-EG',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.60,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  il_yad2: {
    scraperName: 'il_yad2',
    slug: 'il_yad2',
    hosts: ['www.yad2.co.il', 'yad2.co.il'],
    country: 'IL',
    currency: 'ILS',
    localeCode: 'he-IL',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.60,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  hr_njuskalo: {
    scraperName: 'hr_njuskalo',
    slug: 'hr_njuskalo',
    hosts: ['www.njuskalo.hr', 'njuskalo.hr'],
    country: 'HR',
    currency: 'EUR',
    localeCode: 'hr-HR',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.60,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  ro_imobiliare: {
    scraperName: 'ro_imobiliare',
    slug: 'ro_imobiliare',
    hosts: ['www.imobiliare.ro', 'imobiliare.ro'],
    country: 'RO',
    currency: 'EUR',
    localeCode: 'ro-RO',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.60,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  hu_ingatlan: {
    scraperName: 'hu_ingatlan',
    slug: 'hu_ingatlan',
    hosts: ['www.ingatlan.com', 'ingatlan.com'],
    country: 'HU',
    currency: 'HUF',
    localeCode: 'hu-HU',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.60,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  cz_sreality: {
    scraperName: 'cz_sreality',
    slug: 'cz_sreality',
    hosts: ['www.sreality.cz', 'sreality.cz'],
    country: 'CZ',
    currency: 'CZK',
    localeCode: 'cs-CZ',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.60,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  pe_adondevivir: {
    scraperName: 'pe_adondevivir',
    slug: 'pe_adondevivir',
    hosts: ['www.adondevivir.com', 'adondevivir.com'],
    country: 'PE',
    currency: 'USD',
    localeCode: 'es-PE',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.60,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  ec_plusvalia: {
    scraperName: 'ec_plusvalia',
    slug: 'ec_plusvalia',
    hosts: ['www.plusvalia.com', 'plusvalia.com'],
    country: 'EC',
    currency: 'USD',
    localeCode: 'es-EC',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.60,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  pk_zameen: {
    scraperName: 'pk_zameen',
    slug: 'pk_zameen',
    hosts: ['www.zameen.com', 'zameen.com'],
    country: 'PK',
    currency: 'PKR',
    localeCode: 'en-PK',
    areaUnit: 'sqft',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.65,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  id_rumah123: {
    scraperName: 'id_rumah123',
    slug: 'id_rumah123',
    hosts: ['www.rumah123.com', 'rumah123.com'],
    country: 'ID',
    currency: 'IDR',
    localeCode: 'id-ID',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.65,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  vn_batdongsan: {
    scraperName: 'vn_batdongsan',
    slug: 'vn_batdongsan',
    hosts: ['www.batdongsan.com.vn', 'batdongsan.com.vn'],
    country: 'VN',
    currency: 'VND',
    localeCode: 'vi-VN',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.60,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  ua_lun: {
    scraperName: 'ua_lun',
    slug: 'ua_lun',
    hosts: ['www.lun.ua', 'lun.ua'],
    country: 'UA',
    currency: 'UAH',
    localeCode: 'uk-UA',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.60,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  sa_bayut: {
    scraperName: 'sa_bayut',
    slug: 'sa_bayut',
    hosts: ['www.bayut.sa', 'bayut.sa'],
    country: 'SA',
    currency: 'SAR',
    localeCode: 'en-SA',
    areaUnit: 'sqft',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.70,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  ma_mubawab: {
    scraperName: 'ma_mubawab',
    slug: 'ma_mubawab',
    hosts: ['www.mubawab.ma', 'mubawab.ma'],
    country: 'MA',
    currency: 'MAD',
    localeCode: 'fr-MA',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.60,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  lt_aruodas: {
    scraperName: 'lt_aruodas',
    slug: 'lt_aruodas',
    hosts: ['www.aruodas.lt', 'aruodas.lt'],
    country: 'LT',
    currency: 'EUR',
    localeCode: 'lt-LT',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.60,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  bg_imotbg: {
    scraperName: 'bg_imotbg',
    slug: 'bg_imotbg',
    hosts: ['www.imot.bg', 'imot.bg'],
    country: 'BG',
    currency: 'EUR',
    localeCode: 'bg-BG',
    areaUnit: 'sqmt',
    contentSource: 'html',
    supportTier: 'experimental',
    expectedExtractionRate: 0.55,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  sk_nehnutelnosti: {
    scraperName: 'sk_nehnutelnosti',
    slug: 'sk_nehnutelnosti',
    hosts: ['www.nehnutelnosti.sk', 'nehnutelnosti.sk'],
    country: 'SK',
    currency: 'EUR',
    localeCode: 'sk-SK',
    areaUnit: 'sqmt',
    contentSource: 'html',
    supportTier: 'experimental',
    expectedExtractionRate: 0.55,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  rs_nekretnine: {
    scraperName: 'rs_nekretnine',
    slug: 'rs_nekretnine',
    hosts: ['www.nekretnine.rs', 'nekretnine.rs'],
    country: 'RS',
    currency: 'EUR',
    localeCode: 'sr-RS',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.55,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  si_nepremicnine: {
    scraperName: 'si_nepremicnine',
    slug: 'si_nepremicnine',
    hosts: ['www.nepremicnine.net', 'nepremicnine.net'],
    country: 'SI',
    currency: 'EUR',
    localeCode: 'sl-SI',
    areaUnit: 'sqmt',
    contentSource: 'html',
    supportTier: 'experimental',
    expectedExtractionRate: 0.55,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  lv_city24: {
    scraperName: 'lv_city24',
    slug: 'lv_city24',
    hosts: ['www.city24.lv', 'city24.lv'],
    country: 'LV',
    currency: 'EUR',
    localeCode: 'lv-LV',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.55,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  ee_city24: {
    scraperName: 'ee_city24',
    slug: 'ee_city24',
    hosts: ['www.city24.ee', 'city24.ee'],
    country: 'EE',
    currency: 'EUR',
    localeCode: 'et-EE',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.55,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  cy_bazaraki: {
    scraperName: 'cy_bazaraki',
    slug: 'cy_bazaraki',
    hosts: ['www.bazaraki.com', 'bazaraki.com'],
    country: 'CY',
    currency: 'EUR',
    localeCode: 'en-CY',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.55,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  lu_athome: {
    scraperName: 'lu_athome',
    slug: 'lu_athome',
    hosts: ['www.athome.lu', 'athome.lu'],
    country: 'LU',
    currency: 'EUR',
    localeCode: 'fr-LU',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.60,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  jp_suumo: {
    scraperName: 'jp_suumo',
    slug: 'jp_suumo',
    hosts: ['www.suumo.jp', 'suumo.jp'],
    country: 'JP',
    currency: 'JPY',
    localeCode: 'ja-JP',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'manual-only',
    expectedExtractionRate: 0.55,
    stripTrailingSlash: false,
    requiresJsRendering: true,
  },
  kr_zigbang: {
    scraperName: 'kr_zigbang',
    slug: 'kr_zigbang',
    hosts: ['www.zigbang.com', 'zigbang.com'],
    country: 'KR',
    currency: 'KRW',
    localeCode: 'ko-KR',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'manual-only',
    expectedExtractionRate: 0.55,
    stripTrailingSlash: false,
    requiresJsRendering: true,
  },
  tw_591: {
    scraperName: 'tw_591',
    slug: 'tw_591',
    hosts: ['www.591.com.tw', '591.com.tw'],
    country: 'TW',
    currency: 'TWD',
    localeCode: 'zh-TW',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'manual-only',
    expectedExtractionRate: 0.55,
    stripTrailingSlash: false,
    requiresJsRendering: true,
  },
  bd_bproperty: {
    scraperName: 'bd_bproperty',
    slug: 'bd_bproperty',
    hosts: ['www.bproperty.com', 'bproperty.com'],
    country: 'BD',
    currency: 'BDT',
    localeCode: 'en-BD',
    areaUnit: 'sqft',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.60,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  lk_ikman: {
    scraperName: 'lk_ikman',
    slug: 'lk_ikman',
    hosts: ['www.ikman.lk', 'ikman.lk'],
    country: 'LK',
    currency: 'LKR',
    localeCode: 'en-LK',
    areaUnit: 'sqft',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.55,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  gh_meqasa: {
    scraperName: 'gh_meqasa',
    slug: 'gh_meqasa',
    hosts: ['www.meqasa.com', 'meqasa.com'],
    country: 'GH',
    currency: 'USD',
    localeCode: 'en-GH',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.55,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  uy_infocasas: {
    scraperName: 'uy_infocasas',
    slug: 'uy_infocasas',
    hosts: ['www.infocasas.com.uy', 'infocasas.com.uy'],
    country: 'UY',
    currency: 'USD',
    localeCode: 'es-UY',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.60,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  cr_encuentra24: {
    scraperName: 'cr_encuentra24',
    slug: 'cr_encuentra24',
    hosts: ['www.encuentra24.com', 'encuentra24.com'],
    country: 'CR',
    currency: 'USD',
    localeCode: 'es-CR',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.55,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
  do_supercasas: {
    scraperName: 'do_supercasas',
    slug: 'do_supercasas',
    hosts: ['www.supercasas.com', 'supercasas.com'],
    country: 'DO',
    currency: 'USD',
    localeCode: 'es-DO',
    areaUnit: 'sqmt',
    contentSource: 'json-ld',
    supportTier: 'experimental',
    expectedExtractionRate: 0.55,
    stripTrailingSlash: false,
    requiresJsRendering: false,
  },
};

/**
 * Build additional portal configs from mapping metadata.
 * Mappings with a `portal` key get auto-registered.
 * Hardcoded entries in PORTAL_REGISTRY take precedence.
 */
function buildAutoDiscoveredPortals(): Record<string, PortalConfig> {
  const discovered: Record<string, PortalConfig> = {};
  try {
    const mappings = allMappings();
    for (const [name, mapping] of Object.entries(mappings)) {
      if (!mapping.portal) continue;
      // Skip if already in hardcoded registry
      if (PORTAL_REGISTRY[name]) continue;
      discovered[name] = {
        scraperName: name,
        slug: name,
        hosts: mapping.portal.hosts,
        country: mapping.portal.country,
        currency: mapping.portal.currency,
        localeCode: mapping.portal.localeCode,
        areaUnit: mapping.portal.areaUnit,
        contentSource: mapping.portal.contentSource || 'html',
        supportTier: 'experimental',
        ...(mapping.expectedExtractionRate != null
          ? { expectedExtractionRate: mapping.expectedExtractionRate }
          : {}),
        stripTrailingSlash: mapping.portal.stripTrailingSlash || false,
        requiresJsRendering: mapping.portal.requiresJsRendering || false,
      };
    }
  } catch {
    // Mapping bundle not available (e.g. during tests without Vite)
  }
  return discovered;
}

/** Merged registry: hardcoded + auto-discovered from mapping metadata. */
const mergedRegistry: Record<string, PortalConfig> = {
  ...buildAutoDiscoveredPortals(),
  ...PORTAL_REGISTRY, // hardcoded takes precedence
};

/** Reverse index: hostname -> PortalConfig */
const hostIndex = new Map<string, PortalConfig>();
for (const config of Object.values(mergedRegistry)) {
  for (const host of config.hosts) {
    hostIndex.set(host, config);
  }
}

export function findPortalByHost(hostname: string): PortalConfig | undefined {
  return hostIndex.get(hostname);
}

export function findPortalByName(name: string): PortalConfig | undefined {
  return mergedRegistry[name];
}

export function allPortalNames(): string[] {
  return Object.keys(mergedRegistry);
}
